// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtgQxdXBDoY0Qax31vpwX6i0G8_OSkOt8',
    appId: '1:1087008729387:web:ba949a2a3623483a76fd6e',
    messagingSenderId: '1087008729387',
    projectId: 'soltion-center',
    authDomain: 'soltion-center.firebaseapp.com',
    storageBucket: 'soltion-center.appspot.com',
    measurementId: 'G-EVQGY59VXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARd0KiLHa4Ot44o9eKd0GWZDUK-OBod_Q',
    appId: '1:1087008729387:android:76a8399b148387f776fd6e',
    messagingSenderId: '1087008729387',
    projectId: 'soltion-center',
    storageBucket: 'soltion-center.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAYwy2JvFMj5tLyzHd90s3U4U81y-z08o',
    appId: '1:1087008729387:ios:cb65ae0dd32fa82476fd6e',
    messagingSenderId: '1087008729387',
    projectId: 'soltion-center',
    storageBucket: 'soltion-center.appspot.com',
    iosClientId: '1087008729387-kk2alham02d32mf1512h2l6ollpmnr5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.soltionCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAYwy2JvFMj5tLyzHd90s3U4U81y-z08o',
    appId: '1:1087008729387:ios:d9b221157e081a2c76fd6e',
    messagingSenderId: '1087008729387',
    projectId: 'soltion-center',
    storageBucket: 'soltion-center.appspot.com',
    iosClientId: '1087008729387-g2ngo3bdi1kc4ltilamjrrff24emunpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.soltionCenter.RunnerTests',
  );
}
